name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
    - name: Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get upgrade -y
        sudo apt-get install -y libudev-dev libgl-dev libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build
      run: |
        cmake -B build
        cmake --build build

  tests_linux:
    needs: build-linux
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      # - name: Cache Criterion
      #   id: cache-criterion
      #   uses: actions/cache@v3
      #   with:
      #     path: ./Criterion
      #     key: ${{ runner.os }}-Criterion
    - name: Install criterion
        # if: steps.cache-criterion.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install gcovr
          sudo apt-get install meson
          git clone --recursive https://github.com/Snaipe/Criterion Criterion
          cd Criterion
          meson build
          ninja -C build
          sudo ninja -C build install

    - name: Make Criterion available
      run: |
        cd Criterion
        sudo ldconfig

    - name: Build
      run: make run_tests

    - name: Coverage report
      run: |
        mkdir -p coverage
        gcovr -e tests --html-details coverage/coverage.html

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: Coverage-report
        path: ./coverage

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: ./coverage
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_DIR: docs/coverage