name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linter:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Linter
      uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: 'sources'
        clangFormatVersion: 13
        inplace: False

  build-linux:
    needs: linter
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Dependencies
      run: ${GITHUB_WORKSPACE}/.github/workflows/scripts/install_dependencies.sh

    - name: Build
      run: |
        cmake -B build
        cmake --build build

  build-windows:
    needs: linter
    runs-on: windows-2019
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Dependencies
      run: git submodule update --init --recursive

    - name: Build
      run: |
        cmake -B build
        cmake --build build

  tests_linux:
    needs: build-linux
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Dependencies
      run: ${GITHUB_WORKSPACE}/.github/workflows/scripts/install_dependencies.sh criterion

    - name: Build
      run: make run_tests

    - name: Coverage report
      run: |
        mkdir -p coverage
        gcovr -e tests -e ECS --html-details coverage/index.html
        gcovr -e tests -e ECS --xml coverage.xml

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: Coverage-report
        path: ./coverage

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: ./coverage
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_DIR: docs/coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3