name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-22.04
    steps:
      - name: Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y

      - name: Install criterion
        run: |
          sudo apt-get install gcovr
          sudo apt-get install meson
          git clone --recursive https://github.com/Snaipe/Criterion Criterion
          cd Criterion
          meson build
          ninja -C build
          sudo ninja -C build install
          sudo ldconfig

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build tests
        run: |
          cmake -B build -DTESTING=ON
          cmake --build build
      
      - name: run tests
        run: ./vector_tests 2>> $GITHUB_STEP_SUMMARY

      - name: coverage
        run: |
          echo "_____________" >> $GITHUB_STEP_SUMMARY
          gcovr -e tests >> $GITHUB_STEP_SUMMARY
          gcovr -e tests branch >> $GITHUB_STEP_SUMMARY
