name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: Cache Criterion
      #   id: cache-criterion
      #   uses: actions/cache@v3
      #   with:
      #     path: ./Criterion
      #     key: ${{ runner.os }}-Criterion

      - name: Install criterion
        # if: steps.cache-criterion.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install gcovr
          sudo apt-get install meson
          git clone --recursive https://github.com/Snaipe/Criterion Criterion
          cd Criterion
          meson build
          ninja -C build
          sudo ninja -C build install
      
      - name: Make criterion available
        run: |
          cd Criterion
          sudo ldconfig

      - name: Build tests
        run: |
          cmake -B build -DTESTING=ON
          cmake --build build
      
      - name: run tests
        run: |
          ./vector_tests 2>> $GITHUB_STEP_SUMMARY
          ./ecs_tests 2>> $GITHUB_STEP_SUMMARY

      - name: coverage
        run: |
          mkdir -p coverage
          gcovr -e tests --html-details coverage/coverage.html

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: Coverage-report
          path: ./coverage

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ./coverage
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_DIR: coverage